PandoraBox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from contents import views


urlpatterns = [
    path('',include('pages.urls')),
    path('userdetails/', include('userdetails.urls')),
    path('channels/', include('channels.urls')),
    path('contents/', include('contents.urls')),
    #path('search', include('contents.urls')),
    #path('searchb', include('contents.urls')),
    #path('contentlist', include('contents.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contents/urls.py
from django.contrib import admin
from django.urls import path
from contents import views

#from django.conf.urls import include, url
from django.conf import settings  
from django.conf.urls.static import static  
from django.contrib.auth import views as auth_views
#from users import views as user_views


urlpatterns = [
    path('', views.search_view, name='search'),
    path('search', views.search_view, name='search'),
    path('contentlist', views.contentlist_view, name='contentlist'),
    path('contentins', views.content_insert_view, name='contentins'), 
    path('contentinsertb', views.content_insertb_view, name='contentinsertb'),     
    path('<int:content_id>', views.content, name='content'),
    path('contentupdate/<int:id>', views.content_update_view, name='contentupdate'),   
]


#if settings.DEBUG:
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('support', views.support, name='support'),
    path('otherservices', views.otherservices, name='otherservices'),    
    #path('creators', views.creators, name='creators'), 
    path('creatorbox', views.creatorbox, name='creatorbox')
]

contents/models.py
# ===============================================
# filename......: /contents/model.py
# purpose.......: create model for contents
# date created..: 2023-2-14
# date modified.: 2023-2-15
# created by....: Jacky Chan
# ===============================================

from django.db import models
from datetime import date, datetime
from userdetails.models import Userdetail
from channels.models import Channel
#DATE_INPUT_FORMATS = ['%Y-%m-%d']
# pow = models.BooleanField(default=False)

class Content(models.Model):  
    channel     = models.ForeignKey(Channel, on_delete=models.DO_NOTHING)
    user        = models.ForeignKey(Userdetail, on_delete=models.DO_NOTHING)
    title       = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    level       = models.IntegerField()
    image       = models.ImageField(upload_to='images/')
    video       = models.FileField(upload_to='videos/', null=True, blank=True)
    videolink   = models.CharField(max_length=250, null=True, blank=True)
    youtubelink = models.CharField(max_length=250, null=True, blank=True)
    dateupload  = models.DateTimeField(default=datetime.now)
    tag         = models.CharField(max_length=250, null=True, blank=True)
 
    def __str__(self):
        return self.title



class Contentmedia(models.Model):  
    content     = models.ForeignKey(Content, on_delete=models.DO_NOTHING)
    channel     = models.ForeignKey(Channel, on_delete=models.DO_NOTHING)
    user        = models.ForeignKey(Userdetail, on_delete=models.DO_NOTHING)
    media_type  = models.CharField(max_length=1, null=True, blank=True) 
    media_name  = models.CharField(max_length=100, null=True, blank=True)
    media_path  = models.CharField(max_length=200, null=True, blank=True)
    media_image = models.ImageField(upload_to='images/')
 
    def __str__(self):
        return self.content.title

contents/forms.py
from django import forms  
from contents.models import Content  
class Contentform(forms.ModelForm):  
    class Meta:  
        model = Content
        fields = "__all__"  


#fields = ('eid','face','good','hire_date','eemail')

contents/views.py
from django.shortcuts import render, redirect
import datetime
import time
import os
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
# add now
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# from django.conf import settings
from django.core.mail import send_mail
from django.template import loader
from django.http import HttpResponse, HttpResponseNotFound
# add 2023-2-1
from django.contrib import messages
from PandoraBox import settings
from channels.models import Channel
from contents.models import Content
from userdetails.models import Userdetail
from contents.forms import Contentform
from subscriptions.models import Subscription
from django.views.decorators.http import require_http_methods
# @require_http_methods(["GET"])


def search_view(request):
    # userdetail = User_detail.objects.all().order_by('id')
    keywords = request.GET['keywords']
    querylist = Content.objects.filter(
        tag__icontains=keywords).order_by('-dateupload')
    paginator = Paginator(querylist, 3)
    page = request.GET.get('page')
    paged_querylist = paginator.get_page(page)

    context = {
        'listings': paged_querylist,
        'keywords': keywords
    }
    return render(request, "contents/search.html", context)


 


def contentlist_view(request):
    content_list = Content.objects.all()
    paginator = Paginator(content_list, 2)  # Show 2 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'contentlist.html', {'page_obj': page_obj})


def content_insert_view(request, template_name='contents/content_ins_form.html'):
    if request.method == 'POST':
        form = Contentform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('channels')
    else:
        form = Contentform()
    return render(request, template_name, {'form': form})



def content_insertb_view(request):
    if request.method == 'POST':
        channel     = request.POST['channel']
        user        = request.POST['user']
        title       = request.POST['title']
        description = request.POST['description']
        level       = request.POST['level']
        image       = request.POST['image']
        video       = request.POST['video']
        videolink   = request.POST['videolink']
        youtubelink = request.POST['youtubelink']
        dateupload  = request.POST['dateupload']
        tag         = request.POST['tag']
        content = Content.objects.create(channel=channel, user=user, title=title, description=description, level=level, image=image, video=video, videolink=videolink, youtubelink=youtubelink, dateupload=dateupload, tag=tag)
        messages.success(request, 'content record is now inserted!')
        return redirect('creators')
    else:
        context = {
            'vchannel': 'testchannel',
            'vuser' : 'test'
        }    
        return render(request, 'contents/content_insert.html')
    


def content(request, content_id):
    content = Content.objects.all().filter(id=content_id)
    channel_id = Content.objects.values_list(
        'channel_id').filter(id=content_id)[0]
    if Subscription.objects.values_list(
            'level').order_by('-level').filter(channel_id=channel_id, user_id=request.user.id).exists():
        subscription = Subscription.objects.values_list(
            'level').order_by('-level').filter(channel_id=channel_id, user_id=request.user.id)[0]
        subscription = subscription[0]
    else:
        subscription = 0
    print(subscription)
    context = {
        'content': content,
        'subscription': subscription,
    }
    return render(request, 'contents/content.html', context)


def content_update_view(request, id):
    content = Content.objects.all().filter(id=id).first()
    form = Contentform(request.POST, instance=content)
    if form.is_valid():
        form.save()
        return redirect("creatorbox")
    return render(request, "contents/content_update.html", {'content': content})

templates/contents/channel_ins_form2.html
{% extends "base.html" %}
<!-- extends base.html -->
{% load static %}
<!-- load static -->
{% block content %}
<!-- block content -->

<!-- ======= Breadcrumbs ======= -->
<section class="breadcrumbs">
  <div class="container">
    <ol>
      <li><a href="index.html">Home</a></li>
      <li>Chontents</li>
    </ol>
    <h2>Content -Insert</h2>
  </div>
</section>
<!-- End Breadcrumbs -->

 
<section class="inner-page">
  <div class="container">
    <!---->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">
        <header class="section-header">
          <p>Content - Insert</p>
        </header>


 
<form method="post"  enctype="multipart/form-data">
        {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Insert</button>
</form>

 
    </section>
    <!-- End Portfolio Section -->
    <!-- end block -->
    {% endblock %}
  </div>
</section>
 

templates/contents/channel_ins_form3.html
{% extends "base.html" %}
<!-- extends base.html -->
{% load static %}
<!-- load static -->
{% block content %}
<!-- block content -->

<!-- ======= Breadcrumbs ======= -->
<section class="breadcrumbs">
  <div class="container">
    <ol>
      <li><a href="index.html">Home</a></li>
      <li>Chontents</li>
    </ol>
    <h2>Content -Insert</h2>
  </div>
</section>
<!-- End Breadcrumbs -->

 
<section class="inner-page">
  <div class="container">
    <!---->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">
        <header class="section-header">
          <p>Content - Insert</p>
        </header>


 
<form method="post"  enctype="multipart/form-data">
        {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Insert</button>
</form>

 
    </section>
    <!-- End Portfolio Section -->
    <!-- end block -->
    {% endblock %}
  </div>
</section>
 

templates/contents/content-20230217.html
{% extends "base.html" %}
<!-- extends base.html -->
{% load static %}
<!-- load static -->
{% block content %}
<!-- block content -->

<!-- ======= Breadcrumbs ======= -->
<section class="breadcrumbs">
  <div class="container">
    <ol>
      <li><a href="index.html">Home</a></li>
      <li>Channels</li>
    </ol>
    <h2>Content</h2>
  </div>
</section>
<!-- End Breadcrumbs -->
<div class="container">
<!---->
{% if content %}
<!---->
{% for content in content %}
<!---->
<br>
<img src="{{content.user.user_icon.url}}" />
<br /><hr>
user : {{content.user}}
<br /><hr>
content title : {{content.title}}
<br /><hr>
content description : {{content.description}}
<br /><hr>
content image : <img src="{{content.image.url}}" />
<br /><hr>
content dateupload : {{content.dateupload}}
<br /><hr>
content tag : {{content.tag}}
<br /><hr>
<!---->
{% endfor %}
<!---->
{% else %}
<!---->
<p>No Content</p>
<!---->
</div>
{% endif %}
<!-- end block -->
{% endblock %}

templates/contents/content.html
<!-- #====================================================================== -->
<!-- # filename......: templates/contents/content.html                       -->
<!-- # purpose.......: to display a particular content from model Content    -->
<!-- # date created..: 2023-2-12                                             -->
<!-- # date modified.: 2023-2-18                                             -->
<!-- # modify detail.: add author info at the bottom                         -->
<!-- # version.......: 2.0                                                   -->
<!-- # file creator..: Jacky Chan                                            -->
<!-- # detail info...: See at the end of the file                            -->
<!-- #====================================================================== -->

{% extends "base.html" %}
<!-- extends base.html -->
{% load static %}
<!-- load static -->
{% block content %}
<!-- block content -->
{% if content %}
<!---->
{% for content in content %}

<!-- ======= Breadcrumbs ======= -->
<section class="breadcrumbs">
  <div class="container">
    <ol>
      <li><a href="/">Home</a></li>
      <li>Content</li>
    </ol>
    <h2>{{ content.title }}</h2>
  </div>
</section><!-- End Breadcrumbs -->
 
{% if content.user.id == user.id  %}   <!--  if same user -->
<!-- author bio -->
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">

    <div class="row">
      <div class="col-lg-12 entries">
        <div class="blog-author d-flex align-items-center">
          <img src="{{content.channel.icon.url}}" class="rounded-circle float-left" alt="" />
          <div>
            <h4>{{content.channel}}</h4>
            <div class="social-links">
              <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
              <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
              <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
            </div>
            <p>{{content.channel.description}}</p>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12 entries">
        <div class="plyr__video-embed" id="player-youtube">
          <iframe src="{{content.youtubelink}}"></iframe>
        </div>
        <script>
          const playerYoutube = new Plyr("#player-youtube", {
            controls: [
              "play-large", // The large play button in the center
              "restart", // Restart playback
              "rewind", // Rewind by the seek time (default 10 seconds)
              "play", // Play/pause playback
              "fast-forward", // Fast forward by the seek time (default 10 seconds)
              "progress", // The progress bar and scrubber for playback and buffering
              "current-time", // The current time of playback
              "duration", // The full duration of the media
              "mute", // Toggle mute
              "volume", // Volume control
              "captions", // Toggle captions
              "settings", // Settings menu
              "pip", // Picture-in-picture (currently Safari only)
              "airplay", // Airplay (currently Safari only)
              "download", // Show a download button with a link to either the current source or a custom URL you specify in your options
              "fullscreen", // Toggle fullscreen
            ],
          });
        </script>
      </div>
    </div>

  </div>
</section>
<!-- End blog author bio -->
<!-- hidden -->
{% elif content.level > subscription %}
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">
    <div class="row">
      <div class="col-lg-12 entries">
        <div class="blog-author d-flex align-items-center">
          <img src="{{content.channel.icon.url}}" class="rounded-circle float-left" alt="" />
          <div>
            <h4>{{content.channel}}</h4>
            <div class="social-links">
              <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
              <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
              <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
            </div>
            <p>{{content.channel.description}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% else %}
<!-- author bio -->
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">

    <div class="row">
      <div class="col-lg-12 entries">
        <div class="blog-author d-flex align-items-center">
          <img src="{{content.channel.icon.url}}" class="rounded-circle float-left" alt="" />
          <div>
            <h4>{{content.channel}}</h4>
            <div class="social-links">
              <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
              <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
              <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
            </div>
            <p>{{content.channel.description}}</p>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12 entries">
        <div class="plyr__video-embed" id="player-youtube">
          <iframe src="{{content.youtubelink}}"></iframe>
        </div>
        <script>
          const playerYoutube = new Plyr("#player-youtube", {
            controls: [
              "play-large", // The large play button in the center
              "restart", // Restart playback
              "rewind", // Rewind by the seek time (default 10 seconds)
              "play", // Play/pause playback
              "fast-forward", // Fast forward by the seek time (default 10 seconds)
              "progress", // The progress bar and scrubber for playback and buffering
              "current-time", // The current time of playback
              "duration", // The full duration of the media
              "mute", // Toggle mute
              "volume", // Volume control
              "captions", // Toggle captions
              "settings", // Settings menu
              "pip", // Picture-in-picture (currently Safari only)
              "airplay", // Airplay (currently Safari only)
              "download", // Show a download button with a link to either the current source or a custom URL you specify in your options
              "fullscreen", // Toggle fullscreen
            ],
          });
        </script>
      </div>
    </div>

  </div>
</section>
<!-- End blog author bio -->
<!-- hidden -->
{% endif %}

<!-- ======= Blog Single Section ======= -->

<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">

    <div class="row">

      <div class="col-lg-8 entries">
        {% if content.user.id == user.id  %}
        <article class="entry entry-single">

          <div class="entry-img"> <!-- show content image, title -->
            <img src="{{ content.image.url }}" alt="content.image" class="img-fluid">
          </div>
          <h2 class="entry-title">
            <a href="blog-single.html">{{ content.title }}</a>
          </h2>

          <div class="entry-meta"> <!-- show author name, dateupload -->
            <ul>
              <li class="d-flex align-items-center"><i class="bi bi-person"></i>
                  {{ content.channel.link }}</li>
              <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <time
                    datetime="2023-02-05">{{ content.dateupload }}</time></li>

            </ul>
          </div>

          <div class="entry-content">

            <blockquote>
              <p>
                Description
              </p>
            </blockquote>

            <p> {{ content.description }} </p>
          </div>


        </article><!-- End blog entry -->
        {% elif content.level > subscription %}
        
        <article class="entry entry-single">

          <div class="entry-img img-filter"> <!-- show content image, title -->
            <img src="{{ content.image.url }}" alt="content.image" class="img-fluid">
          </div>
        </article>
        <h1><font color=red>please subscribe to view content</font></h1>
        <h2><a href="/channels/{{ content.channel.id}}/{{ content.channel.link}}#membership">click here to subscribe</a></h2><br>
       
        {% else %}              <!-- show content if subscribe -->
        <article class="entry entry-single">

          <div class="entry-img"> <!-- show content image, title -->
            <img src="{{ content.image.url }}" alt="content.image" class="img-fluid">
          </div>
          <h2 class="entry-title">
            <a href="blog-single.html">{{ content.title }}</a>
          </h2>

          <div class="entry-meta"> <!-- show author name, dateupload -->
            <ul>
              <li class="d-flex align-items-center"><i class="bi bi-person"></i>
                  {{ content.channel.link }}</li>
              <li class="d-flex align-items-center"><i class="bi bi-clock"></i><time
                    datetime="2023-02-05">{{ content.dateupload }}</time></li>

            </ul>
          </div>

          <div class="entry-content">

            <blockquote>
              <p>
                Description
              </p>
            </blockquote>

            <p> {{ content.description }} </p>
          </div>


        </article><!-- End blog entry -->
        {% endif %}

        <div class="blog-author d-flex align-items-center">
          <!--    assets/img/logo.png -->
          <img src="{{content.user.user_icon.url}}" class="rounded-circle float-left" alt="deutschland">
          <div>
            <h4>{{ content.user }}</a></h4>
            <div class="social-links">
              <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
              <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
              <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
            </div>
            <p> {{ content.user.country }} </p>
          </div>
        </div><!-- End blog author bio -->
        {% endfor %}
        <!---->
        {% else %}
        <!---->
        <p>No Content</p>
        <!---->

        {% endif %}


      </div><!-- End blog entries list -->

      <div class="col-lg-4"> <!-- blog sidebar -->
        <div class="sidebar"> <!-- right-hand side side bar -->
          <h3 class="sidebar-title">Search</h3>
          <div class="sidebar-item search-form">
            <form action="search">
                <input type="search" name="keywords">
                <button type="submit"><i class="bi bi-search"></i></button>
            </form>
          </div><!-- End sidebar search formn-->
        </div><!-- End sidebar -->
      </div><!-- End blog sidebar -->

    </div>

  </div>
</section><!-- End Blog Single Section -->

</main><!-- End #main -->




<!-- end block -->
{% endblock %}


<!-- #============================================================================= -->
<!-- # date comment....: 2023-2-12 10:00                                            -->
<!-- # comment by......: Jacky Chan                                                 -->
<!-- # filename........: templates/contents/content.html                            -->
<!-- # version.........: 1.0                                                        -->
<!-- # purpose.........: to display a particular content from model Content         -->
<!-- # language........: Django, python                                             -->
<!-- # server os.......: ubuntu 22.10                                               -->
<!-- # server location.: Tseung Kwan O, iAdvantage Data Centre Section A, Rack 23   -->
<!-- #                                                                              -->
<!-- # The logic of this program                                                    -->
<!-- # for loop                                                                     -->
<!-- #      show channel info                                                       -->
<!-- #      show content video                                                      -->
<!-- #      show content image                                                      -->
<!-- #      show description                                                        -->
<!-- #      show author info                                                        -->
<!-- #                                                                              -->
<!-- # show right-hand sidebar                                                      -->
<!-- #      search form                                                             -->
<!-- #      popular channel                                                         -->
<!-- #      recent content                                                          -->
<!-- #      tag                                                                     -->
<!-- #                                                                              -->
<!-- #============================================================================= -->

<!-- #============================================================================= -->
<!-- # date comment....: 2023-2-18 18:00                                            -->
<!-- # comment by......: Jacky Chan                                                 -->
<!-- # version.........: 2.0                                                        -->
<!-- # modify detail...: to display the author detail at the lower part             -->
<!-- # ============================================================================ -->

<!-- --------------------------- end of the file ---------------------------------- -->

templates/contents/content_insert.html
{% extends 'base.html' %}
{% block content %}
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">
        <ol>
            <li><a href="">Home</a></li>
            <li>Content</li>
        </ol>
        <h2>Content - Insert</h2>
        </div>
    </section>
    <!-- End Breadcrumbs -->
    <!--Register form                        {x% url 'insertb' %x} --> 
    <div class="container">
        <br>
        <form action="contentinsert" method="POST">
            {% csrf_token %}
            <br>
            <div class="form-group">
                <label for="channel">Channel</label>
                <input type="text" class="form-control" name="channel" id="channel" value="" >
            </div>
            <br>
            <div class="form-group">
                <label for="user">User</label>
                <input type="text" class="form-control" name="user" id="user" value="" >
            </div>
            <br>
              
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" required>
            </div>
            <br>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" class="form-control" name="description" id="description" >
            </div>
            <br>
            <div class="form-group">
                <label for="level">Level</label>
                <input type="text" class="form-control" name="level" id="level" >
            </div>
            <br>
            <div class="form-group">
                <label for="image">Image</label>
                <input type="file" class="form-control" name="image" id="image" >
            </div>
            <br>
            <div class="form-group">
                <label for="video">Video</label>
                <input type="file" class="form-control" name="video" id="video" >
            </div>
            <br>
            <div class="form-group">
                <label for="videolink">Video Link</label>
                <input type="text" class="form-control" name="videolink" id="videolink" >
            </div>
            <br>
            <div class="form-group">
                <label for="youtubelink">Youtube Link</label>
                <input type="text" class="form-control" name="youtubelink" id="youtubelink" >
            </div>
            <br>
            <div class="form-group">
                <label for="dateupload">Date Upload</label>
                <input type="datetime" class="form-control" name="dateupload" id="dateupload" >
            </div>
            <br>

            <div class="form-group">
                <label for="tag">Tag</label>
                <input type="text" class="form-control" name="tag" id="tag" >
            </div>
            <br>

            <input type="submit" value="insert" class="btn btn-secondary btn-block" />
        </form>
        <br>
    </div>
{% endblock %}

templates/contents/content_update.html
{% extends 'base.html' %}
{% block content %}

<!-- ======= Breadcrumbs ======= -->
<section class="breadcrumbs">
  <div class="container">
    <ol>
      <li><a href="{% url 'channels' %}">Home</a></li>
      <li><a href="{% url 'channels' %}">Content</a></li>
    </ol>
    <h2>xxx{{content.title}} yyy   {{content.tag}}  </h2>
  </div>
</section>
<!-- End Breadcrumbs -->


<div class="container">

<form method="POST" class="post-form" action="contentupdate/{{content.id}}">  
        {% csrf_token %}  
    <div class="container">  
     <br>  
     <div class="form-group row">  
       <label class="col-sm-1 col-form-label"></label>  
       <div class="col-sm-4">  
          <h3>content update</h3>  
       </div>  
     </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Title:</label>  
    <div class="col-sm-4">  
        <input type="text" name="title" id="id_title" required maxlength="200" value="{{ content.title }}" />  
    </div>  
  </div>  
  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Youtube Link:</label>  
    <div class="col-sm-4">  
        <input type="text" name="youtubelink" id="youtubelink" maxlength="250" value="{{ content.youtubelink }}" />  
    </div>  
  </div>  
  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Description:</label>  
    <div class="col-sm-4">  
        <input type="text" name="description" id="id_description" required maxlength="500" value="{{ content.description }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Level:</label>  
    <div class="col-sm-4">  
        <input type="text" name="level" id="id_level" value="{{ content.level}}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Tag:</label>  
    <div class="col-sm-4">  
        <input type="text" name="tag" id="id_tag" maxlength="200" value="{{ content.tag }}" />  
    </div>  
  </div>  
  
  <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  

<br><br>
after update, will go to creatorbox 
<br><br>
 
<a href="">index</a><br>
 <a href="/creatorbox">back to creatorbox</a> 
</div>
{% endblock %}