PandoraBox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from contents import views


urlpatterns = [
    path('',include('pages.urls')),
    path('userdetails/', include('userdetails.urls')),
    path('channels/', include('channels.urls')),
    path('contents/', include('contents.urls')),
    #path('search', include('contents.urls')),
    #path('searchb', include('contents.urls')),
    #path('contentlist', include('contents.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

channels/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.channels, name='channels'),
    path('<int:id>/<slug:link>', views.channel, name='channel'),
    path('', include('contents.urls')),
    # path('index2', views.index2, name='index2'),
    path('subscription', views.subscription, name='subscription'),
    # path('memberships', views.memberships, name='memberships'),
    path('channelins', views.channel_insert_view, name='channelinsert'), 
    path('searchchannelcontent', views.search_channel_content_view, name='searchchannelcontent'),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('support', views.support, name='support'),
    path('otherservices', views.otherservices, name='otherservices'),    
    #path('creators', views.creators, name='creators'), 
    path('creatorbox', views.creatorbox, name='creatorbox')
]

channels/models.py
from django.db import models
from datetime import datetime
from userdetails.models import Userdetail
from django.contrib.auth.models import User
# Create your models here.


class Channel(models.Model):
    #owner_id = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(Userdetail, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    link = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    start_date = models.DateTimeField(default=datetime.now, blank=True)
    icon = models.ImageField(upload_to='photos/channels/%Y/%m/%d', blank=True)
    banner = models.ImageField(upload_to='photos/channels/%Y/%m/%d', blank=True)
    video = models.CharField(max_length=200)
    category = models.CharField(choices=[('IT','IT'),('music','music'),('games','games'),('finance','finance'),('style','style'),('fashion','fashion'),('food','food')],max_length=200)
    status = models.CharField(max_length=1)
    tag = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title

channels/forms.py
from django import forms  
from channels.models import Channel  
class ChannelForm(forms.ModelForm):  
    class Meta:  
        model = Channel  
        fields = ('title','link','description','start_date','icon','banner','video','category','status','tag')
        
        
        
#fields = "__all__"  
#fields = ('eid','face','good','hire_date','eemail')

channels/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .models import Channel
# from userdetails.models import Userdetail
from memberships.models import Membership
from contents.models import Content
from subscriptions.models import Subscription
from userdetails.models import Userdetail
from channels.forms import ChannelForm
from django.contrib import messages
# Create your views here.


def channels(request):
    channels = Channel.objects.all().order_by('id')
    paginator = Paginator(channels, 6)
    page = request.GET.get('page')
    paged_channels = paginator.get_page(page)
    context = {
        'channels': paged_channels  # channels
    }
    return render(request, 'channels/channels.html', context)

# /([0-9])\.+/g
# {% <command>%} {% endcomment%}


def channel(request, id, link):
    channel = get_object_or_404(Channel, link=link)
    memberships = Membership.objects.all().order_by('level').filter(channel_id=id)
    rcontents = Content.objects.all().order_by(
        '-dateupload').filter(channel_id=id)[:5]
    contents = Content.objects.all().order_by('-dateupload').filter(channel_id=id)
    paginator = Paginator(contents, 3)
    page = request.GET.get('page')
    paged_contents = paginator.get_page(page)

    contentsLV = Content.objects.all().order_by(
        '-dateupload').filter(channel_id=id).count()

    contentsLV1 = Content.objects.all().order_by(
        '-dateupload').filter(channel_id=id, level=1).count()

    contentsLV2 = Content.objects.all().order_by(
        '-dateupload').filter(channel_id=id, level=2).count()

    contentsLV3 = Content.objects.all().order_by(
        '-dateupload').filter(channel_id=id, level=3).count()

    if Subscription.objects.values_list(
            'level').order_by('-level').filter(channel_id=id, user_id=request.user.id).exists():
        subscription = Subscription.objects.values_list(
            'level').order_by('-level').filter(channel_id=id, user_id=request.user.id)[0]
        subscription = subscription[0]
    else:
        subscription = 0

    context = {
        'channel': channel,
        'memberships': memberships,
        'contents': paged_contents,
        'recent_contents': rcontents,
        'subscription': subscription,
        'contentsLV': contentsLV,
        'contentsLV1': contentsLV1,
        'contentsLV2': contentsLV2,
        'contentsLV3': contentsLV3,
    }

    return render(request, 'channels/channel.html', context)


def subscription(request):
    if request.method == "POST":
        channel_id = request.POST['channel_id']
        channel_url = request.POST['channel_url']
        membership_level = request.POST['membership_level']

        #
        obj, created = Subscription.objects.update_or_create(
            user_id=request.user.id, channel_id=channel_id, level=membership_level
        )
        print('/channels/' + channel_id + '/' + channel_url)
        if created:
            print("aaa")
            return redirect('/channels/' + channel_id + '/' + channel_url + '#membership')

        # obj.save()
        #
        else:
            print("bbb")
            return redirect('/channels/' + channel_id + '/' + channel_url + '#membership')

        
def channel_insert_view(request, template_name='channels/channel_ins_form.html'):
    if request.method == 'POST':
          form = ChannelForm(request.POST, request.FILES)
          if form.is_valid():
            form.save()
            return redirect('channels')
    else:
            form = ChannelForm()
    return render(request, template_name, {'form':form})


#def channel_insert_view(request):
#    if request.method == 'POST':
#        user = request.POST['user']
#        title = request.POST['title']
#        link = request.POST['link']
#        description = request.POST['description']
#        start_date = request.POST['start_date']
#        icon = request.POST['icon']
#        banner = request.POST['banner']
#        video = request.POST['video']
#        category = request.POST['category']
#        status = request.POST['status']
#        tag = request.POST['tag']
#        channel = Channel.objects.create(user=user, title=title, link=link, description=description, start_date=start_date, icon=icon, banner=banner, video=video, category=category, status=status, tag=tag)
#        messages.success(request, 'content record is now inserted!')
#        return redirect('creators')
#    else:
#        context = {
#            'vchannel': 'TheoDavis Mercedes',
#            'vuser' : 'peggy'
#        }    
#        return render(request, 'channels/channel_insert.html')
    

def search_channel_content_view(request):
        #userdetail = User_detail.objects.all().order_by('id')
        keywords = request.GET['keywords']
        cid = request.GET['cid']
        querylist = Content.objects.filter(tag__icontains=keywords,channel_id=cid).order_by('-dateupload').values()
        paginator = Paginator(querylist, 3)
        page = request.GET.get('page')
        paged_querylist = paginator.get_page(page)
        context = {
            'listings': paged_querylist,
            'keywords' : keywords
        }    
        return render(request,"contents/search.html",context )  

templates/channels/channel_ins_form.html
{% extends "base.html" %}
<!-- extends base.html -->
{% load static %}
<!-- load static -->
{% block content %}
<!-- block content -->

<!-- ======= Breadcrumbs ======= -->
<section class="breadcrumbs">
  <div class="container">
    <ol>
      <li><a href="index.html">Home</a></li>
      <li>Channels</li>
    </ol>
    <h2>Channel -Insert</h2>
  </div>
</section>
<!-- End Breadcrumbs -->

 
<section class="inner-page">
  <div class="container">
    <!---->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">
        <header class="section-header">
          <p>Channel - Insert</p>
        </header>


 
<form method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Insert</button>
</form>

 
    </section>
    <!-- End Portfolio Section -->
    <!-- end block -->
    {% endblock %}
  </div>
</section>
 

templates/channels/channel_ins_form0.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee</title>  
     {% load static %}  
    <!link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">  
</head>  
<body>  
<!div class="container">
 <!-- navbar with responsive toggle-->
 <nav class="navbar navbar-expand-md navbar-dark bg-success mb-3">
    <div class="container">
        <a href="#" class="navbar-brand">PandoraBox</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"><span
                class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="index" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="/channels" class="nav-link">List</a>
                </li>
                <li class="nav-item">
                    <a href="/channelins" class="nav-link">Add</a>
                </li>
                <li class="nav-item">
                    <a href="/admin" target=_blank class="nav-link">Admin</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!/div>

<h1>Channel Create</h1>
<form method="post"  enctype="multipart/form-data">
        {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Insert</button>
</form>

<br><br>



<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
crossorigin="anonymous"></script>
</body>
</html>

templates/channels/channel_insert.html
{% extends 'base.html' %}
{% block content %}
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">
        <ol>
            <li><a href="">Home</a></li>
            <li>Channel</li>
        </ol>
        <h2>Channel - Insert</h2>
        </div>
    </section>
    <!-- End Breadcrumbs -->
    <!--Register form                        {x% url 'insertb' %x} --> 
    <div class="container">
        <br>
        <form action="contentinsert" method="POST">
            {% csrf_token %}
            <br>
            <div class="form-group">
                <label for="channel">User</label>
                <input type="text" class="form-control" name="user" id="user" value="{{ ???? }}" required>
            </div>
            <br>
            <div class="form-group">
                <label for="user">Title</label>
                <input type="text" class="form-control" name="user" id="user" value="{{ ???? }}" required>
            </div>
            <br>
              
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" required>
            </div>
            <br>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" class="form-control" name="description" id="description" required>
            </div>
            <br>
            <div class="form-group">
                <label for="level">Level</label>
                <input type="text" class="form-control" name="level" id="level" required>
            </div>
            <br>
            <div class="form-group">
                <label for="image">Image</label>
                <input type="file" class="form-control" name="image" id="image" >
            </div>
            <br>
            <div class="form-group">
                <label for="video">Video</label>
                <input type="file" class="form-control" name="video" id="video" >
            </div>
            <br>
            <div class="form-group">
                <label for="videolink">Video Link</label>
                <input type="text" class="form-control" name="videolink" id="videolink" required>
            </div>
            <br>
            <div class="form-group">
                <label for="youtubelink">Youtube Link</label>
                <input type="text" class="form-control" name="youtubelink" id="youtubelink" required>
            </div>
            <br>
            <div class="form-group">
                <label for="dateupload">Date Upload</label>
                <input type="datetime" class="form-control" name="dateupload" id="dateupload" >
            </div>
            <br>

            <div class="form-group">
                <label for="tag">Tag</label>
                <input type="text" class="form-control" name="tag" id="tag" required>
            </div>
            <br>

            <input type="submit" value="insert" class="btn btn-secondary btn-block" />
        </form>
        <br>
    </div>
{% endblock %}

templates/channels/channel_update.html
{% extends 'base.html' %}
{% block content %}

<!-- ======= Breadcrumbs ======= -->
<section class="breadcrumbs">
  <div class="container">
    <ol>
      <li><a href="{% url 'channels' %}">Home</a></li>
      <li><a href="{% url 'channels' %}">Channels</a></li>
    </ol>
    <h2>{{channel.title}}</h2>
  </div>
</section>
<!-- End Breadcrumbs -->


<div class="container">

<form method="POST" class="post-form" action="">  
        {% csrf_token %}  
    <div class="container">  
     <br>  
     <div class="form-group row">  
       <label class="col-sm-1 col-form-label"></label>  
       <div class="col-sm-4">  
          <h3>Channel Update</h3><br> 
       </div>  
     </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Title:</label>  
    <div class="col-sm-4">  
        <input type="text" name="title" id="id_title" required maxlength="200" value="{{ channel.title }}" />  
    </div>  
  </div>  
  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Link:</label>  
    <div class="col-sm-4">  
        <input type="text" name="link" id="id_link" required maxlength="200" value="{{ channel.link }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Category:</label>  
    <div class="col-sm-4">  
        <input type="text" name="tag" id="id_category" required maxlength="200" value="{{ channel.category }}" />  
    </div>  
  </div>  

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Status:</label>  
    <div class="col-sm-4">  
        <input type="text" name="status" id="id_status" required maxlength="200" value="{{ channel.status }}" />  
    </div>  
  </div>  

 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Descrption:</label>  
    <div class="col-sm-4">  
        <input type="text" name="description" id="id_status" required maxlength="200" value="{{ channel.description }}" />  
    </div>  
  </div>  


  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Tag:</label>  
    <div class="col-sm-4">  
        <input type="text" name="tag" id="id_tag" required maxlength="200" value="{{ channel.tag }}" />  
    </div>  
  </div>  

 
 


  <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  

<br><br>
after update, will go to creatorbox  {{channel.tag}} {{tag}}
<br><br>
 
<a href="">index</a><br>
 <a href="/creatorbox">back to creatorbox</a> 
</div>
{% endblock %}

templates/channels/channels.html
{% extends "base.html" %}
<!-- extends base.html -->
{% load static %}
<!-- load static -->
{% block content %}
<!-- block content -->

<!-- ======= Breadcrumbs ======= -->
<section class="breadcrumbs">
  <div class="container">
    <ol>
      <li><a href="index.html">Home</a></li>
      <li>Channels</li>
    </ol>
    <h2>Channels</h2>
  </div>
</section>
<!-- End Breadcrumbs -->

<section class="inner-page">
  <div class="container">
    <!---->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">
        <header class="section-header">
          <p>Channel</p>
        </header>

        <h3>
          <center>Popular Searches</center>
        </h3>
        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
            <ul id="portfolio-flters">
              <li data-filter="*" class="filter-active">All</li>
              <li data-filter=".filter-it">I.T.</li>
              <li data-filter=".filter-finance">Finance</li>
              <li data-filter=".filter-style">Style</li>
              <li data-filter=".filter-music">Music</li>
              <li data-filter=".filter-games">Games</li>

              <li data-filter=".filter-fashion">Fashion</li>
              <li data-filter=".filter-food">Food</li>

            </ul>
          </div>
        </div>

        <div class="row gy-4 portfolio-container" data-aos="fade-up" data-aos-delay="200">
          <!---->
          {% if channels %} {% for channel in channels %}
          {% if channel.category == "IT" %}
          <div class="col-lg-4 col-md-6 portfolio-item filter-it">
            {% elif channel.category == "music" %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-music">
              {% elif channel.category == "games" %}
              <div class="col-lg-4 col-md-6 portfolio-item filter-games">
                {% elif channel.category == "finance" %}
                <div class="col-lg-4 col-md-6 portfolio-item filter-finance">
                  {% elif channel.category == "style" %}
                  <div class="col-lg-4 col-md-6 portfolio-item filter-style">
                    {% elif channel.category == "fashion" %}
                    <div class="col-lg-4 col-md-6 portfolio-item filter-fashion">
                      {% elif channel.category == "food" %}
                      <div class="col-lg-4 col-md-6 portfolio-item filter-food">
                {% else %}
                <div class="col-lg-4 col-md-6 portfolio-item filter-other">
                  {% endif %}
                  <div class="portfolio-wrap">
                    <img src="{{channel.icon.url}}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                      <h4>{{channel.title}}</h4>
                      <p>{{channel.user}}</p>
                      <div class="portfolio-links">

                        <a href="{% url 'channel' channel.id channel.link %}" title="More Details"><i
                            class="bi bi-link"></i></a>
                      </div>
                    </div>
                  </div>
                </div>
                <!---->
                {% endfor %} {% else %}
                <p>No Channel Available</p>
                {% endif %}
                <!---->
              </div>
            </div>

          </div>
          <!-- pagination -->
          <div class="blog">
            <div class="blog-pagination">
              {% if channels.has_other_pages %}
              <!-- class="pagination" -->
              <ul class="justify-content-center pagination">
                {% if channels.has_previous %}
                <li class="page-items">
                  <a href="?page={{channels.previous_page_number}}" class="page-link">&laquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="">&laquo;</a>
                </li>
                {% endif %}
                <!-- loop the database content -->
                {% for i in channels.paginator.page_range %}
                <!-- break the page and show the page number -->
                {% if channels.number == i %}
                <li class="page-item active">
                  <a class="page-link">{{i}}</a>
                </li>
                {% else %}
                <li class="page-item">
                  <a href="?page={{i}}" class="page-link">{{i}}</a>
                </li>
                {% endif %}
                <!-- end if -->
                {% endfor %}
                <!-- right arrow -->
                {% if channels.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{channels.next_page_number}}">&raquo;</a>
                </li>
                {% else %}
                <li class="page-item disable">
                  <a class="page-link">&raquo;</a>
                </li>
                {% endif %}
              </ul>
              {% endif %}
              <!-- end loop -->
            </div>
          </div>
          <!-- End blog entries list -->
    </section>
    <!-- End Portfolio Section -->
    <!-- end block -->
    {% endblock %}
  </div>
</section>